/*
Ch.1 SQL 튜닝을 위한 준비
- 관리자로 로그인 필수 (Toad에서는 Connect as를 sysdba로 설정)
*/
-- 1.1 테이블 스페이스 및 계정 생성
-- 1.1.1 테이블스페이스 생성

-- 2) 테이블스페이스 생성
CREATE TABLESPACE DBMSEXPERT_DATA
DATAFILE 'C:\Tools\Oracle\oradata\orcl\DBMSEXPERT_DATA.DBF' SIZE 4G
AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

-- 3) 임시 테이블 스페이스 생성
CREATE TEMPORARY TABLESPACE DBMSEXPERT_TMP
TEMPFILE 'C:\Tools\Oracle\oradata\orcl\DBMSEXPERT_TMP.DBF' SIZE 1G
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;



/*
1.1.2 사용자 계정 생성
2) 사용자 계정 생성
- 지금부터 DBMSEXPERT 계쩡으로 로그인하여 생성하는 테이블 및 인덱스는 모두
  DBMSEXPERT_DATA에 생성됨
- 해당 계정으로 작업하다 임시 영역이 필요한 경우 DBMSEXPERT_TMP 영역 사용
*/
CREATE USER DBMSEXPERT IDENTIFIED BY DBMSEXPERT -- IDENTIFIED BY [비밀번호]
DEFAULT TABLESPACE DBMSEXPERT_DATA
TEMPORARY TABLESPACE DBMSEXPERT_TMP
PROFILE DEFAULT
ACCOUNT UNLOCK;

-- 3) 권한 부여
GRANT RESOURCE TO DBMSEXPERT;
GRANT CONNECT TO DBMSEXPERT;
GRANT CREATE VIEW TO DBMSEXPERT;
GRANT CREATE SYNONYM TO DBMSEXPERT;